### ISSUE TITLE
User can search and select a Ghibli Movie to review.

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search and select a Ghibli Movie to review.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the search bar and choose a Ghibli Movie to review from the dropdown.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="275" alt="Screen Shot 2021-07-26 at 1 04 07 PM" src="https://user-images.githubusercontent.com/85139853/127051620-75e04654-a251-49ab-8a37-222a73caf5c9.png">

<img width="279" alt="Screen Shot 2021-07-26 at 1 04 36 PM" src="https://user-images.githubusercontent.com/85139853/127051684-b963b667-d74e-4a02-b04b-49b890b0a502.png">

<img width="780" alt="Screen Shot 2021-07-26 at 1 05 03 PM" src="https://user-images.githubusercontent.com/85139853/127051732-f92a1c74-da5d-4ac9-a087-758aee1b3d35.png">

<img width="810" alt="Screen Shot 2021-07-26 at 1 05 30 PM" src="https://user-images.githubusercontent.com/85139853/127051784-2e750f50-ed09-4755-acdf-1aaf3160aa2d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="home-screen"]` to the HTML.
- [x] Add a link for 'My Reviews'.
- [x] Add a logo of the application to the page.
- [x] Add a `<form>` tag for the movie selection.
- [x] Add a `<select>` tag for the movies and create the respective label.
- [x] Append each movie title to the `'<select>'` tag to have the titles show on the dropdown.
- [x] Make sure the movies are listed in alphabetical order for better user experience.
- [x] Add a submit button.
- [x] Make sure a selection of a movie is required to submit.
- [x] Listen for `'submit'` event on the home-screen.
- [x] Make sure form is resetting after `'submit'`.
- [x] Make sure the elements are styled to match the screenshots.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
