### ISSUE TITLE
User can see the total number of reviews they wrote and see introduction modal for first visit

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the total number of reviews they wrote.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see the number of reviews they wrote.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-08-05 at 10 41 44 PM](https://user-images.githubusercontent.com/85139853/128461939-a30cd3fc-9a58-4335-ad0e-04c576929d98.png)

![Screen Shot 2021-08-05 at 10 43 03 PM](https://user-images.githubusercontent.com/85139853/128461971-bf8fb63a-6abf-490f-86ee-5c6e12307a64.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal to show on user's first visit.
- [x] Make sure the modal only shows up on the user's first visit.
- [x] Have a button for the user to close the modal.
- [x] Compare the movie titles in the API to the movie titles in the data model to see how many movies were reviewed out of all the movies.
- [x] Add the number along with text in the HTML to show how many of the movies the user has reviewed.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
