### ISSUE TITLE
User can add a review.

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a review.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add/create a review of the movie they chose in the home-screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-28 at 9 58 26 PM](https://user-images.githubusercontent.com/85139853/127434224-a3991d6f-d886-4c6e-9d13-a3efd9c8eda2.png)

![Screen Shot 2021-07-28 at 9 58 57 PM](https://user-images.githubusercontent.com/85139853/127434265-b9f43b24-92f1-47d4-9d05-839015737f59.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="review-form"]`.
- [x] Create a data-model that contains: view, reviews, editing, and nextReviewId.
- [x] Add a form for creating a review to the `div[data-view="review-form"]`.
- [x] Make sure the form is populated with the title, description, and image of the movie the user chose in the home-screen. (Image is not included in API. Pull from internet)
- [x] Make the input required.
- [x] Make a save button to save review.
- [x] Listen for `'submit'` event on the review-form and:
     - [x] Create a `dataObject` with the movie title, image, description, and review.
     - [x] Add the `nextReviewId` to the data model and increment it.
     - [x] Unshift the created 'dataObject' to the `reviews` property in the data model.
     - [x] Reset the form input.
- [x] Verify that new reviews are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new review receives an incrementing `reviewId` which is inside the `dataObject`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
