### ISSUE TITLE
Refactor to ES6

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#22]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change all `var`s to `const` and `let`.
- [x] Use template literals for any string concatenation.
- [x] Use `arrow-function` notation where it can be used.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
