### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#28]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Remove margin and center search bar/button on home-screen.
- [x] Add padding to search bar for movies.
- [x] Change heading bars to heading tags instead of div tags.
- [x] Remove colons.
- [x] Move edit and delete icon to the review bar from the movie title bar.
