### ISSUE TITLE
User can view reviews.

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view reviews.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see their saved review(s) after saving it through the form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="207" alt="Screen Shot 2021-07-30 at 10 04 50 AM" src="https://user-images.githubusercontent.com/85139853/127687658-81f68a1e-50bd-4c44-9b97-1160e1130dce.png">

<img width="210" alt="Screen Shot 2021-07-29 at 12 39 20 PM" src="https://user-images.githubusercontent.com/85139853/127555374-116d6397-68a2-4baf-924d-ee15a4c6e963.png">

<img width="604" alt="Screen Shot 2021-07-30 at 10 04 05 AM" src="https://user-images.githubusercontent.com/85139853/127687584-9a433c3a-476f-48c5-a3ca-e3a292c56246.png">

<img width="618" alt="Screen Shot 2021-07-29 at 12 40 14 PM" src="https://user-images.githubusercontent.com/85139853/127555508-36b1080a-775d-47c9-b4bb-3c849932d76f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="review-gallery"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="review-gallery"]` element in the HTML.
- [x]  Add some dummy review to the unordered list in the HTML and style them to match the wireframe.
- [x] Define a function that takes a single review object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each review in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML reviews once the user's entries are successfully being appended to the DOM on page load.
- [x]  Add a navigation item to the navbar for My Reviews that functions.
- [x]  Ensure that submitting a new review  also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new review automatically shows the `'review-gallery'` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.(If on form, make refreshing go back to the home page)
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
