### ISSUE TITLE
User can edit a review.

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a review.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to select an existing review to edit and pre-populate its information into the form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="211" alt="Screen Shot 2021-07-30 at 10 34 23 AM" src="https://user-images.githubusercontent.com/85139853/127690698-7ad8e8cc-e565-4a0e-a2fc-c62acb630f42.png">

<img width="212" alt="Screen Shot 2021-07-30 at 10 34 42 AM" src="https://user-images.githubusercontent.com/85139853/127690739-0310ccff-bac8-4248-81eb-cf5bb1cd4cfb.png">

<img width="606" alt="Screen Shot 2021-07-30 at 10 35 16 AM" src="https://user-images.githubusercontent.com/85139853/127690798-57aaca9e-c39f-40cb-9caf-fb979149c545.png">

<img width="604" alt="Screen Shot 2021-07-30 at 10 35 57 AM" src="https://user-images.githubusercontent.com/85139853/127690880-7482b39a-c6b7-479e-9a9b-b7ea25be54ec.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update review rendering function to include an edit icon for each rendered review.
- [x] Ensure that each rendered review is given a `data-review-id` attribute indicating which review it is.
- [x] Listen for clicks on the parent element of all rendered reviews.
- [x] Show the review form if an edit icon was clicked.
- [x] Find the matching review object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the review form with the clicked review's values from the object found in the data model.
- [x] Update the review form's submit handler function to conditionally add a new review object or update the existing one.
- [x] Update the review form's submit handler function to conditionally add a new review DOM tree or replace the existing one.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
