### ISSUE TITLE
User can delete a review.

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/my-ghibli-movie-review#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a review.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow users to delete a review from the review-gallery.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="210" alt="Screen Shot 2021-07-30 at 3 51 21 PM" src="https://user-images.githubusercontent.com/85139853/127718909-7e876cc7-5f56-4343-b196-ab85ac3e2cad.png">

<img width="209" alt="Screen Shot 2021-07-30 at 3 51 56 PM" src="https://user-images.githubusercontent.com/85139853/127718933-b621587d-edb3-42cc-973a-8cabf0b74115.png">

<img width="613" alt="Screen Shot 2021-07-30 at 3 52 32 PM" src="https://user-images.githubusercontent.com/85139853/127718949-e3a801ee-0962-4440-8b6c-dfea1180d8d7.png">

<img width="612" alt="Screen Shot 2021-07-30 at 3 53 05 PM" src="https://user-images.githubusercontent.com/85139853/127718989-02bb7a19-5bcc-47b5-a1cb-8c6dbf212508.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target icon for deleting a review on the review-gallery.
- [x] Show a confirmation modal when the user clicks the delete icon.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the review from the data model and the review's DOM tree from the page if the user clicks Delete.
- [x] Show the review gallery if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
